apply plugin: 'com.android.library'

group = 'expo.modules.smsreader'
version = '1.0.0'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useExpoPublishing()

def useManagedAndroidSdkVersions = false
if (useManagedAndroidSdkVersions) {
  useDefaultAndroidSdkVersions()
} else {
  android {
    namespace "expo.modules.smsreader"
    compileSdkVersion safeExtGet("compileSdkVersion", 36)
    defaultConfig {
      minSdkVersion safeExtGet("minSdkVersion", 24)
      targetSdkVersion safeExtGet("targetSdkVersion", 36)
    }
    lintOptions {
      abortOnError false
    }
  }
}

private def safeExtGet(String prop, Object fallback) {
  rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

dependencies {
  implementation project(':expo-modules-core')
}
